
###
GET http://localhost:8080/api/admin/games

###

GET http://localhost:8080/api/admin/games/5


###
POST http://localhost:8080/api/admin/games
Content-Type: application/json

{
  "homeTeam": "aaaa",
  "awayTeam": "blblaaab",
  "homeScore": 0,
  "awayScore": 0,
  "gameDate": "2025-09-07T15:00:00",
  "gameStatus": "SCHEDULED"
}

###
PUT http://localhost:8080/api/admin/games/134
Content-Type: application/json

{
  "homeTeam": "zzzz",
  "awayTeam": "ssss",
  "homeScore": 0,
  "awayScore": 0,
  "gameDate": "2025-09-07T15:00:00",
  "gameStatus": "SCHEDULED"
}

###
DELETE http://localhost:8080/api/admin/games/134